### ISSUE TITLE
Oauth not working for users other then who created the application

### ISSUE THREAD

**Issue by satishpandey** [magott/spring-social-yammer#4]
Hello,

I am using this package to connect yammer user accounts. It am able to connect the user account who created the application but for other users it's not working. Also if i remove the token from the connected account (same who created the application), i am not able to reconnect it.

I tried with POST/GET both but nothing works for me..

--------------------------------------------------------------------------- Sample Stack Trace ----------------------------------------------------

2012-Jun-20 16:41:24  WARN [http-8080-1] org.apache.http.impl.client.DefaultHttpClient:1095 - Authentication error: Unable to respond to any of these challenges: {}
2012-Jun-20 16:41:24  WARN [http-8080-1] org.springframework.web.client.RestTemplate:478 - GET request for "https://www.yammer.com/oauth2/access_token?client_id=zlFlQNVPwAL2EdBefl8Ow&client_secret=3aUo5FpsU8oDqYW24NQtEFxtBniMM14Gt6m7lT6Lcs&code=GA8HWbcqk461mWOk4uLcQ" resulted in 401 (Unauthorized); invoking error handler
2012-Jun-20 16:41:24 DEBUG [http-8080-1] org.apache.http.wire:63 - << "2e[\r][\n]"
2012-Jun-20 16:41:24 DEBUG [http-8080-1] org.apache.http.wire:77 - << "Code supplied does not match the Request Token"
2012-Jun-20 16:41:24 DEBUG [http-8080-1] org.apache.http.wire:63 - << "[\r][\n]"
2012-Jun-20 16:41:24 DEBUG [http-8080-1] org.apache.http.wire:63 - << "0[\r][\n]"
2012-Jun-20 16:41:24 DEBUG [http-8080-1] org.apache.http.wire:63 - << "[\r][\n]"

**Comment by magott** [comment]
Hi,

I believe this is down to Yammer. They only allow one user per application (for testing). When you want your app to become "official" you have to get it authorized by the yammer people. I'm not 100% sure what the process is. Try asking at the developer network. If you haven't signed up for it (it is basically a yammer network for developers doing yammer apps), you can do so here: https://www.yammer.com/yammerdevelopersnetwork

Once your app is authorized it should work for all users. Please let me know if this helps.

**Comment by magott** [comment]
Found some more information for you:
Go to https://www.yammer.com/client_applications
Select your application
Then you'll probably see the following under Availability:
Enabled: Yes
Networks:  `<your network>`
File a support ticket to allow all users on all networks to use this application.

So, what you have to do is to click the link to file a support ticket, then Yammer should help you out to make your app available for all users (on all networks)

**Comment by satishpandey** [comment]
Thank you Magott for sharing this info.
